apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: demo
data:
  OTEL_SERVICE_NAME: "backend"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-svc.monitoring.svc.cluster.local:4317"
  PORT: "8001"
