apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rca-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
