apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-kubelet
rules:
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/metrics", "nodes/proxy", "pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-kubelet-binding
subjects:
  - kind: ServiceAccount
    name: otel-collector-sa
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: otel-collector-kubelet
  apiGroup: rbac.authorization.k8s.io
